package com.fxplatform.common.exception;

import java.util.Set;

public final class ErrorCode {

  public static final String AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED";
  public static final String AUTH_REFRESH_TOKEN_INVALID = "AUTH_REFRESH_TOKEN_INVALID";
  public static final String USER_DISABLED = "USER_DISABLED";
  public static final String ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND";
  public static final String ACCOUNT_NOT_ACTIVE = "ACCOUNT_NOT_ACTIVE";
  public static final String SYMBOL_NOT_TRADABLE = "SYMBOL_NOT_TRADABLE";
  public static final String QUOTE_STALE = "QUOTE_STALE";
  public static final String INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE";
  public static final String INSUFFICIENT_MARGIN = "INSUFFICIENT_MARGIN";
  public static final String ORDER_NOT_CANCELABLE = "ORDER_NOT_CANCELABLE";
  public static final String ORDER_ALREADY_FILLED = "ORDER_ALREADY_FILLED";
  public static final String DUPLICATE_CLIENT_ORDER_ID = "DUPLICATE_CLIENT_ORDER_ID";
  public static final String EXECUTION_UNAVAILABLE = "EXECUTION_UNAVAILABLE";
  public static final String EXECUTION_DISABLED = "EXECUTION_DISABLED";
  public static final String DEMO_ACCOUNT_REQUIRED = "DEMO_ACCOUNT_REQUIRED";
  public static final String PRODUCT_NOT_ALLOWED = "PRODUCT_NOT_ALLOWED";
  public static final String SYMBOL_NOT_ALLOWED = "SYMBOL_NOT_ALLOWED";
  public static final String MARKET_DATA_UNAVAILABLE = "MARKET_DATA_UNAVAILABLE";
  public static final String MARKET_DATA_STALE = "MARKET_DATA_STALE";
  public static final String MARKET_BUNDLE_INCOMPLETE = "MARKET_BUNDLE_INCOMPLETE";
  public static final String INVALID_CANDLE_REQUEST = "INVALID_CANDLE_REQUEST";
  public static final String PARTIAL_FILL_NOT_SUPPORTED = "PARTIAL_FILL_NOT_SUPPORTED";
  public static final String INVALID_QUANTITY_UNIT = "INVALID_QUANTITY_UNIT";
  public static final String QUANTITY_CONVERTS_TO_ZERO = "QUANTITY_CONVERTS_TO_ZERO";
  public static final String INVALID_SPOT_ORDER_TYPE = "INVALID_SPOT_ORDER_TYPE";
  public static final String INVALID_SPOT_ORDER_FIELDS = "INVALID_SPOT_ORDER_FIELDS";
  public static final String ORDER_PRICE_REQUIRED = "ORDER_PRICE_REQUIRED";
  public static final String ORDER_TRIGGER_PRICE_REQUIRED = "ORDER_TRIGGER_PRICE_REQUIRED";
  public static final String OCO_PRICE_RELATION_INVALID = "OCO_PRICE_RELATION_INVALID";
  public static final String OCO_GROUP_INCOMPLETE = "OCO_GROUP_INCOMPLETE";
  public static final String OCO_ORDER_NOT_MODIFIABLE = "OCO_ORDER_NOT_MODIFIABLE";
  public static final String ORDER_HOLD_INVALID = "ORDER_HOLD_INVALID";
  public static final String DEMO_RESET_BLOCKED = "DEMO_RESET_BLOCKED";
  public static final String TRANSFER_AMOUNT_INVALID = "TRANSFER_AMOUNT_INVALID";
  public static final String TRANSFER_AMOUNT_UNAVAILABLE = "TRANSFER_AMOUNT_UNAVAILABLE";
  public static final String TRANSFER_REQUEST_CONFLICT = "TRANSFER_REQUEST_CONFLICT";

  private static final Set<String> STANDARD_CODES = Set.of(
      AUTH_TOKEN_EXPIRED,
      AUTH_REFRESH_TOKEN_INVALID,
      USER_DISABLED,
      ACCOUNT_NOT_FOUND,
      ACCOUNT_NOT_ACTIVE,
      SYMBOL_NOT_TRADABLE,
      QUOTE_STALE,
      INSUFFICIENT_BALANCE,
      INSUFFICIENT_MARGIN,
      ORDER_NOT_CANCELABLE,
      ORDER_ALREADY_FILLED,
      DUPLICATE_CLIENT_ORDER_ID,
      EXECUTION_UNAVAILABLE,
      EXECUTION_DISABLED,
      DEMO_ACCOUNT_REQUIRED,
      PRODUCT_NOT_ALLOWED,
      SYMBOL_NOT_ALLOWED,
      MARKET_DATA_UNAVAILABLE,
      MARKET_DATA_STALE,
      MARKET_BUNDLE_INCOMPLETE,
      INVALID_CANDLE_REQUEST,
      PARTIAL_FILL_NOT_SUPPORTED,
      INVALID_QUANTITY_UNIT,
      QUANTITY_CONVERTS_TO_ZERO,
      INVALID_SPOT_ORDER_TYPE,
      INVALID_SPOT_ORDER_FIELDS,
      ORDER_PRICE_REQUIRED,
      ORDER_TRIGGER_PRICE_REQUIRED,
      OCO_PRICE_RELATION_INVALID,
      OCO_GROUP_INCOMPLETE,
      OCO_ORDER_NOT_MODIFIABLE,
      ORDER_HOLD_INVALID,
      DEMO_RESET_BLOCKED,
      TRANSFER_AMOUNT_INVALID,
      TRANSFER_AMOUNT_UNAVAILABLE,
      TRANSFER_REQUEST_CONFLICT);

  private ErrorCode() {
  }

  public static Set<String> standardCodes() {
    return STANDARD_CODES;
  }
}
