import type { TradingMarket } from './tradingModels'

export const mockTradingMarkets: TradingMarket[] = [
  {
    symbol: 'EURUSD',
    base: 'EUR',
    quote: 'USD',
    name: 'Euro / US Dollar',
    category: 'fx',
    favorite: true,
    last: 1.0832,
    changePercent: 0.18,
    volume: '1.28B',
    high24h: 1.0878,
    low24h: 1.0794,
    spread: 0.00004,
    source: 'markets.sources.mock'
  },
  {
    symbol: 'GBPUSD',
    base: 'GBP',
    quote: 'USD',
    name: 'British Pound / US Dollar',
    category: 'fx',
    favorite: true,
    last: 1.2712,
    changePercent: -0.11,
    volume: '842M',
    high24h: 1.2768,
    low24h: 1.2681,
    spread: 0.00005,
    source: 'markets.sources.mock'
  },
  {
    symbol: 'USDJPY',
    base: 'USD',
    quote: 'JPY',
    name: 'US Dollar / Japanese Yen',
    category: 'fx',
    favorite: false,
    last: 156.42,
    changePercent: 0.26,
    volume: '1.04B',
    high24h: 156.88,
    low24h: 155.91,
    spread: 0.01,
    source: 'markets.sources.mock'
  },
  {
    symbol: 'AUDUSD',
    base: 'AUD',
    quote: 'USD',
    name: 'Australian Dollar / US Dollar',
    category: 'fx',
    favorite: false,
    last: 0.6642,
    changePercent: 0.07,
    volume: '392M',
    high24h: 0.6674,
    low24h: 0.6619,
    spread: 0.00004,
    source: 'markets.sources.mock'
  },
  {
    symbol: 'XAUUSD',
    base: 'XAU',
    quote: 'USD',
    name: 'Gold Spot / US Dollar',
    category: 'metals',
    favorite: true,
    last: 2348.4,
    changePercent: -0.32,
    volume: '96K',
    high24h: 2362.8,
    low24h: 2337.2,
    spread: 0.28,
    source: 'markets.sources.mock'
  },
  {
    symbol: 'BTCUSDT',
    base: 'BTC',
    quote: 'USDT',
    name: 'Bitcoin / Tether',
    category: 'crypto',
    favorite: true,
    last: 67240,
    changePercent: 1.42,
    volume: '38.2K',
    high24h: 68120,
    low24h: 65880,
    spread: 4.2,
    source: 'markets.sources.mock'
  },
  {
    symbol: 'ETHUSDT',
    base: 'ETH',
    quote: 'USDT',
    name: 'Ethereum / Tether',
    category: 'crypto',
    favorite: false,
    last: 3420,
    changePercent: 0.84,
    volume: '211K',
    high24h: 3478,
    low24h: 3364,
    spread: 0.9,
    source: 'markets.sources.mock'
  },
  {
    symbol: 'SOLUSDT',
    base: 'SOL',
    quote: 'USDT',
    name: 'Solana / Tether',
    category: 'crypto',
    favorite: false,
    last: 152.12,
    changePercent: 3.25,
    volume: '1.82M',
    high24h: 155,
    low24h: 147.5,
    spread: 0.01,
    source: 'markets.sources.mock'
  },
  {
    symbol: 'XRPUSDT',
    base: 'XRP',
    quote: 'USDT',
    name: 'XRP / Tether',
    category: 'crypto',
    favorite: false,
    last: 2.481,
    changePercent: -1.13,
    volume: '89.23M',
    high24h: 2.56,
    low24h: 2.41,
    spread: 0.002,
    source: 'markets.sources.mock'
  },
  {
    symbol: 'US100',
    base: 'US100',
    quote: 'USD',
    name: 'US Tech 100 Index',
    category: 'indices',
    favorite: false,
    last: 18924.6,
    changePercent: -0.22,
    volume: 'Index',
    high24h: 19034.2,
    low24h: 18872.1,
    spread: 1.2,
    source: 'markets.sources.mock'
  }
]

export const mockDepthLevels = [
  { priceOffset: 3, size: '0.42', side: 'ask' },
  { priceOffset: 2, size: '0.78', side: 'ask' },
  { priceOffset: 1, size: '1.16', side: 'ask' },
  { priceOffset: -1, size: '1.08', side: 'bid' },
  { priceOffset: -2, size: '0.64', side: 'bid' },
  { priceOffset: -3, size: '0.36', side: 'bid' }
] as const
