import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, it } from 'node:test'

const pagesDir = dirname(fileURLToPath(import.meta.url))
const markets = readFileSync(join(pagesDir, 'markets', 'MarketsPage.tsx'), 'utf8')
const orders = readFileSync(join(pagesDir, 'orders', 'OrdersPage.tsx'), 'utf8')
const positions = readFileSync(join(pagesDir, 'positions', 'PositionsPage.tsx'), 'utf8')
const accountPagesPath = join(pagesDir, 'account', 'AccountPages.tsx')
const accountPages = existsSync(accountPagesPath) ? readFileSync(accountPagesPath, 'utf8') : ''
const wallet = readFileSync(join(pagesDir, 'wallet', 'WalletPage.tsx'), 'utf8')
const authSupport = readFileSync(join(pagesDir, 'login', 'AuthSupportPage.tsx'), 'utf8')
const login = readFileSync(join(pagesDir, 'login', 'LoginPage.tsx'), 'utf8')
const authStyles = readFileSync(join(pagesDir, 'login', 'LoginPage.module.css'), 'utf8')
const styles = readFileSync(join(pagesDir, '..', 'styles.css'), 'utf8')
const selectFieldPath = join(pagesDir, '..', 'components', 'SelectField.tsx')
const selectField = existsSync(selectFieldPath) ? readFileSync(selectFieldPath, 'utf8') : ''
const selectFieldCss = styles.slice(styles.indexOf('.select-field {'), styles.indexOf('.app-shell {'))
const marketSortSelectCss = styles.slice(
  styles.indexOf('.market-sort-field .select-field {'),
  styles.indexOf('.market-universe-tabs,'),
)

describe('prototype markets page', () => {
  it('keeps the market API and realtime layer while presenting a Binance-style overview model', () => {
    assert.match(markets, /fetchMarketSymbols/)
    assert.match(markets, /fetchMarketQuote/)
    assert.match(markets, /subscribeQuote/)
    assert.match(markets, /LoadingState/)
    assert.match(markets, /ApiErrorState/)
    assert.match(markets, /formatApiError/)
    assert.match(markets, /mockTradingMarkets/)
    assert.match(markets, /marketPageTabs/)
    assert.match(markets, /overview/)
    assert.match(markets, /trading-data/)
    assert.match(markets, /ai-picks/)
    assert.match(markets, /token-unlocks/)
    assert.match(markets, /marketUniverseTabs/)
    assert.match(markets, /marketZoneTabs/)
    assert.match(markets, /favorites/)
    assert.match(markets, /crypto/)
    assert.match(markets, /forex/)
    assert.match(markets, /contract/)
    assert.match(markets, /spot/)
    assert.match(markets, /all/)
    assert.match(markets, /MarketMobileList/)
    assert.match(markets, /marketColumns/)
    assert.doesNotMatch(markets, /market-shell__hero/)
    assert.match(markets, /market-shell__titleSrOnly/)
    assert.match(markets, /24h成交量/)
    assert.match(markets, /市值/)
    assert.doesNotMatch(markets, /Bid\/Ask|high24h|low24h|sourceStatus/)
  })

  it('uses readable Binance-like market labels for the visible market surface', () => {
    assert.match(markets, /加密货币市场/)
    assert.match(markets, /总览/)
    assert.match(markets, /交易数据/)
    assert.match(markets, /热门币种/)
    assert.match(markets, /涨幅榜/)
    assert.match(markets, /跌幅榜/)
    assert.match(markets, /24h成交量/)
    assert.match(markets, /市值/)
    assert.doesNotMatch(markets, />[^<]*鎬昏/)
  })

  it('uses the requested overview universe tabs and routes the forex tab to provider-backed forex rows', () => {
    const universeTabs = markets.slice(markets.indexOf('const marketUniverseTabs'), markets.indexOf('const marketZoneTabs'))
    assert.match(markets, /const marketUniverseTabs: Array<\{ value: MarketUniverseTab; label: string \}> = \[\s*\{ value: 'favorites', label: '自选' \},\s*\{ value: 'forex', label: '外汇' \},\s*\{ value: 'crypto', label: '币种' \},\s*\{ value: 'spot', label: '现货' \},\s*\{ value: 'contract', label: '合约' \}\s*\]/)
    assert.doesNotMatch(universeTabs, /\{ value: 'all', label:/)
    assert.doesNotMatch(universeTabs, /label: 'TradFi'/)
    assert.match(markets, /universeTab === 'forex'[\s\S]*\? market\.category === 'fx'/)
    assert.match(markets, /fetchMarketSymbols\(\)/)
  })

  it('renders provider symbol lists before quote hydration so forex data is not blocked by every pair quote', () => {
    assert.match(markets, /const marketQuoteHydrationLimit = 40/)
    assert.match(markets, /const initialMarkets = symbols\.length > 0 \? symbols : mockTradingMarkets/)
    assert.match(markets, /setMarkets\(initialMarkets\)/)
    assert.match(markets, /initialMarkets\.filter\(canHydrateMarketQuote\)\.slice\(0, marketQuoteHydrationLimit\)\.map\(\(market\) => loadQuotedMarket\(market\)\)/)
    assert.match(markets, /visibleMarkets\.filter\(canHydrateMarketQuote\)\.slice\(0, marketQuoteHydrationLimit\)/)
    assert.match(markets, /function canHydrateMarketQuote\(market: TradingMarket\)/)
    assert.match(markets, /market\.tradable !== false/)
    assert.match(markets, /market\.category === 'fx'/)
    assert.match(markets, /market\.provider === 'massive'/)
  })

  it('connects market rows to category-aware trading routes and last-symbol memory', () => {
    assert.match(markets, /writeLastTradingSymbol/)
    assert.match(markets, /resolveTradingPath/)
    assert.match(markets, /onOpenMarket/)
    assert.match(markets, /category=\$\{category\}/)
    assert.match(markets, /symbol=\$\{encodeURIComponent\(market\.symbol\)\}/)
  })

  it('adds Binance-style ranking cards without unsupported market scope creep', () => {
    assert.match(markets, /SummaryCard/)
    assert.match(markets, /MarketSummaryDeck/)
    assert.match(markets, /RankingCard/)
    assert.match(markets, /RankingPreviewCard/)
    assert.match(markets, /MarketInsightPlaceholder/)
    assert.match(markets, /热门币种/)
    assert.match(markets, /涨幅榜/)
    assert.match(markets, /跌幅榜/)
    assert.match(markets, /成交榜/)
    assert.match(markets, /U本位合约/)
    assert.match(markets, /币本位合约/)
    assert.doesNotMatch(markets, /Alpha|DEX|C2C/)
  })

  it('uses the reusable dark listbox select for market sorting', () => {
    assert.equal(existsSync(selectFieldPath), true)
    assert.match(markets, /SelectField/)
    assert.doesNotMatch(markets, /<select value=\{sortKey\}/)
    assert.match(selectField, /role="listbox"/)
    assert.match(selectField, /role="option"/)
    assert.match(selectField, /aria-selected/)
    assert.match(styles, /\.select-field__menu/)
    assert.match(styles, /\.select-field__option\[aria-selected="true"\]/)
    assert.match(styles, /\.market-sort-field\s+\.select-field__menu\s*{[\s\S]*bottom:\s*calc\(100% \+ 6px\)/)
    assert.match(styles, /\.market-sort-field\s+\.select-field__menu\s*{[\s\S]*min-width:\s*144px/)
    assert.match(styles, /@media \(prefers-reduced-motion:\s*reduce\)[\s\S]*\.select-field__menu/)
    assert.match(selectFieldCss, /\.select-field\[data-open="true"\]\s+\.select-field__chevron\s*{[\s\S]*transform:\s*rotate\(180deg\)/)
    assert.match(selectFieldCss, /\.select-field__button:hover\s*{[\s\S]*border-color:\s*rgb\(240 185 11 \/ 0\.42\)/)
    assert.match(selectFieldCss, /\.select-field__menu\s*{[\s\S]*border:\s*1px solid var\(--bn-border\)/)
    assert.doesNotMatch(selectFieldCss, /\.select-field__button:hover,\s*\.select-field\[data-open="true"\]\s+\.select-field__button/)
    assert.doesNotMatch(selectFieldCss, /linear-gradient|box-shadow|animation:\s*dropdownIn/)
    assert.doesNotMatch(marketSortSelectCss, /box-shadow/)
  })
})

describe('prototype auth and account center', () => {
  it('moves successful login and registration to account overview', () => {
    assert.match(login, /return '\/account\/overview'/)
    assert.match(authSupport, /navigate\('\/account\/overview'/)
    assert.match(authSupport, /AuthEntryPage/)
  })

  it('implements same-page email or phone registration steps', () => {
    assert.match(authSupport, /channel/)
    assert.match(authSupport, /countryCode/)
    assert.match(authSupport, /identifier/)
    assert.match(authSupport, /password/)
    assert.match(authSupport, /verification/)
    assert.match(authSupport, /checkAuthIdentity/)
    assert.match(authSupport, /sendAuthVerificationCode/)
    assert.doesNotMatch(authSupport, /不做真实|真实注册|不会创建账户/)
  })

  it('uses a Binance-style authentication shell while preserving login and registration APIs', () => {
    assert.match(login, /login\(email\.trim\(\), password\)/)
    assert.match(login, /writeStoredAuthToken\(auth\.accessToken\)/)
    assert.match(authSupport, /checkAuthIdentity/)
    assert.match(authSupport, /sendAuthVerificationCode/)
    assert.match(authSupport, /register\(identifier, password\)/)
    assert.match(authStyles, /\.page\s*{[\s\S]*background:\s*#181a20/)
    assert.match(authStyles, /\.shell\s*{[\s\S]*grid-template-columns:\s*minmax\(0,\s*520px\) 425px/)
    assert.match(authStyles, /\.form\s*{[\s\S]*width:\s*425px[\s\S]*padding:\s*40px[\s\S]*border-radius:\s*24px[\s\S]*border:\s*1px solid #333b47/)
    assert.match(authStyles, /\.submit\s*{[\s\S]*background:\s*#fcd535/)
    assert.match(authStyles, /\.socialButton\s*{[\s\S]*min-height:\s*48px[\s\S]*border:\s*1px solid #434c5a[\s\S]*border-radius:\s*12px/)
    assert.match(authStyles, /\.segmentedControl button\[aria-pressed="true"\]\s*{[\s\S]*background:\s*#fcd535/)
    assert.doesNotMatch(authStyles, /radial-gradient|backdrop-filter|gridDrift/)
  })

  it('creates the account shell and only the prototype account pages', () => {
    assert.equal(existsSync(accountPagesPath), true)
    assert.match(accountPages, /AccountShell/)
    assert.match(accountPages, /AccountOverviewPage/)
    assert.match(accountPages, /AccountAssetsPage/)
    assert.match(accountPages, /FundingRecordsPage/)
    assert.match(accountPages, /TradeOrdersPage/)
    assert.match(accountPages, /KycPage/)
    assert.match(accountPages, /AccountSettingsPage/)
    assert.match(accountPages, /\/account\/overview/)
    assert.match(accountPages, /\/account\/assets/)
    assert.match(accountPages, /\/account\/orders\/funding/)
    assert.match(accountPages, /\/account\/orders\/trades/)
    assert.match(accountPages, /\/account\/security\/kyc/)
    assert.match(accountPages, /\/account\/settings/)
    assert.doesNotMatch(accountPages, /C2C|期权|邀请好友|活动中心|API 管理|返佣|子账户/)
  })

  it('keeps account pages scoped to assets, ledgers, trade orders, KYC and preferences', () => {
    assert.match(accountPages, /AssetSummaryChartCard/)
    assert.match(accountPages, /AssetRangeTabs/)
    assert.match(accountPages, /RecentLedgerPanel/)
    assert.match(accountPages, /AssetAccountCards/)
    assert.match(accountPages, /资金流水/)
    assert.match(accountPages, /交易订单/)
    assert.match(accountPages, /当前委托/)
    assert.match(accountPages, /历史委托/)
    assert.match(accountPages, /历史成交/)
    assert.match(accountPages, /身份认证/)
    assert.match(accountPages, /通知语言/)
  })

  it('remodels account overview into a Binance-style dashboard flow', () => {
    assert.match(accountPages, /AccountProfileSummary/)
    assert.match(accountPages, /AccountOnboardingSteps/)
    assert.match(accountPages, /AccountAssetActionPanel/)
    assert.match(accountPages, /AccountDashboardInsights/)
    assert.match(accountPages, /account-dashboard-layout/)
    assert.match(accountPages, /account-onboarding-grid/)
    assert.match(accountPages, /account-action-strip/)
    assert.match(accountPages, /account-insight-grid/)
    assert.match(styles, /\.account-dashboard-layout/)
    assert.match(styles, /\.account-onboarding-grid/)
    assert.match(styles, /\.account-step-card--active/)
    assert.match(styles, /\.account-action-strip/)
    assert.match(styles, /@media \(max-width:\s*720px\)[\s\S]*\.account-onboarding-grid\s*{[\s\S]*grid-template-columns:\s*1fr/)
  })

  it('skins user pages with black-gold tokens and compact motion', () => {
    assert.match(styles, /--user-page-bg:\s*var\(--bn-bg\)/)
    assert.match(styles, /--user-surface:\s*var\(--bn-surface\)/)
    assert.match(styles, /--user-primary:\s*#f0b90b/)
    assert.match(styles, /\.account-shell/)
    assert.match(styles, /\.market-shell/)
    assert.match(styles, /\.market-shell__titleSrOnly/)
    assert.match(styles, /\.market-zone-tabs/)
    assert.match(styles, /\.market-mobile-list/)
    assert.match(styles, /\.market-ranking-preview-grid/)
    assert.match(styles, /@media \(max-width:\s*640px\)[\s\S]*\.market-table\s*{[\s\S]*display:\s*none/)
    assert.match(styles, /@media \(prefers-reduced-motion:\s*reduce\)/)
  })

  it('remodels wallet into a Binance-style asset dashboard without changing the funding data flow', () => {
    assert.match(wallet, /useTradingSession/)
    assert.match(wallet, /getFundOrders/)
    assert.match(wallet, /createFundOrder/)
    assert.match(wallet, /DataTable/)
    assert.match(wallet, /wallet-page/)
    assert.match(wallet, /wallet-hero-grid/)
    assert.match(wallet, /wallet-balance-card/)
    assert.match(wallet, /wallet-account-grid/)
    assert.match(wallet, /wallet-risk-card/)
    assert.match(wallet, /wallet-action-grid/)
    assert.match(wallet, /wallet-asset-detail/)
    assert.match(wallet, /wallet-workbench/)
    assert.match(wallet, /wallet-sidebar/)
    assert.match(wallet, /wallet-login-gate/)
    assert.match(styles, /\.wallet-page__hero/)
    assert.match(styles, /\.wallet-hero-grid/)
    assert.match(styles, /\.wallet-balance-card/)
    assert.match(styles, /\.wallet-account-grid/)
    assert.match(styles, /\.wallet-risk-card/)
    assert.match(styles, /\.wallet-workbench/)
    assert.match(styles, /\.wallet-sidebar/)
    assert.match(styles, /\.wallet-login-gate/)
    assert.match(styles, /@media \(max-width:\s*720px\)[\s\S]*\.wallet-hero-grid\s*{[\s\S]*grid-template-columns:\s*1fr/)
  })
})

describe('user order page automation hooks', () => {
  it('keeps order actions addressable by backend order identity', () => {
    assert.match(orders, /data-order-id=\{order\.id\}/)
    assert.match(orders, /data-order-status=\{order\.status\}/)
  })

  it('keeps position actions addressable by backend position identity', () => {
    assert.match(positions, /data-position-id=\{position\.id\}/)
    assert.match(positions, /data-position-status=\{position\.status\}/)
  })
})
