package com.fxplatform.engagement.config;

import com.fxplatform.common.exception.BusinessException;
import com.fxplatform.engagement.application.content.ContentAssetStorage;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.regex.Pattern;

/** Development-only filesystem adapter; keys are always generated by ContentAssetService. */
public final class LocalContentAssetStorage implements ContentAssetStorage {

  private static final Pattern TRUSTED_KEY = Pattern.compile(
      "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\\.(jpg|png|webp)");

  private final Path root;

  public LocalContentAssetStorage(Path root) {
    this.root = root.toAbsolutePath().normalize();
  }

  @Override
  public void put(String storageKey, byte[] bytes) {
    Path target = resolve(storageKey);
    if (bytes == null || bytes.length == 0) {
      throw unavailable(null);
    }
    try {
      Files.createDirectories(root);
      Files.write(target, bytes, StandardOpenOption.CREATE_NEW, StandardOpenOption.WRITE);
    } catch (IOException exception) {
      throw unavailable(exception);
    }
  }

  @Override
  public byte[] get(String storageKey, long maximumBytes) {
    Path target = resolve(storageKey);
    try {
      if (maximumBytes <= 0
          || !Files.isRegularFile(target, LinkOption.NOFOLLOW_LINKS)
          || Files.size(target) > maximumBytes) {
        throw unavailable(null);
      }
      return Files.readAllBytes(target);
    } catch (IOException exception) {
      throw unavailable(exception);
    }
  }

  @Override
  public void delete(String storageKey) {
    Path target = resolve(storageKey);
    try {
      Files.deleteIfExists(target);
    } catch (IOException exception) {
      throw unavailable(exception);
    }
  }

  private Path resolve(String storageKey) {
    if (storageKey == null || !TRUSTED_KEY.matcher(storageKey).matches()) {
      throw new BusinessException(
          "CONTENT_ASSET_STORAGE_KEY_INVALID", "Content asset storage key is invalid");
    }
    Path target = root.resolve(storageKey).normalize();
    if (!target.startsWith(root)) {
      throw new BusinessException(
          "CONTENT_ASSET_STORAGE_KEY_INVALID", "Content asset storage key is invalid");
    }
    return target;
  }

  private static BusinessException unavailable(Throwable cause) {
    String code = "CONTENT_ASSET_STORAGE_UNAVAILABLE";
    String message = "Content asset storage is unavailable";
    return cause == null
        ? new BusinessException(code, message)
        : new BusinessException(code, message, cause);
  }
}
