package com.fxplatform.ledger.enums;

/**
 * LedgerEntryType 定义资金流水模块的枚举值。
 */
public enum LedgerEntryType {
  DEMO_INIT,
  DEMO_RESET,
  VALIDATION_SEED,
  TRANSFER_IN,
  TRANSFER_OUT,
  DEMO_DEPOSIT,
  ORDER_HOLD,
  ORDER_RELEASE,
  MARGIN_HOLD,
  MARGIN_RELEASE,
  TRADE_FEE,
  TRADE_PNL,
  FUNDING_FEE,
  FINANCING,
  CONVERSION_FEE,
  LIQUIDATION_FEE,
  BANKRUPTCY_SHORTFALL,
  FORCED_CLOSE,
  ADMIN_ADJUSTMENT
}
